#!/usr/bin/env bash

set -e

CONFIG="install.conf.yaml"
DOTBOT_DIR="dotbot"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASEDIR}"
git -C "${DOTBOT_DIR}" submodule sync --quiet --recursive
git submodule update --init --recursive "${DOTBOT_DIR}"

OHMYZSH_DIR="ohmyzsh"

git -C "${OHMYZSH_DIR}" submodule sync --quiet --recursive
git submodule update --init --recursive "${OHMYZSH_DIR}"

echo $BASEDIR
echo $DOTBOT_DIR
echo $DOTBOT_BIN

"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${CONFIG}" "${@}"
